services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=/api
    ports:
      - '5173:5173'
    depends_on:
      - backend
